{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.706412584",
    "module": "gsyVideoPlayer-armv7a",
    "version": "1.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gsyVideoPlayer-armv7a-1.4.2.aar",
          "url": "gsyVideoPlayer-armv7a-1.4.2.aar",
          "size": 2488803,
          "sha512": "963b59a55990126ba07b9f1484f92de9201fe2f1929682928d146d694380c07d925d94ca1a83f29321f884713b6023692fa1584794b82eaae5faa5488a23183d",
          "sha256": "bd9b480f02a9d8de7183379d047535d1bb906a654d54e4004d094c38e5d51c60",
          "sha1": "b275121e2ebc676150e7cc88e8bb698f037ac6aa",
          "md5": "f6785fc49a020ffb25c08bf16757a735"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "gsyVideoPlayer-armv7a-1.4.2.aar",
          "url": "gsyVideoPlayer-armv7a-1.4.2.aar",
          "size": 2488803,
          "sha512": "963b59a55990126ba07b9f1484f92de9201fe2f1929682928d146d694380c07d925d94ca1a83f29321f884713b6023692fa1584794b82eaae5faa5488a23183d",
          "sha256": "bd9b480f02a9d8de7183379d047535d1bb906a654d54e4004d094c38e5d51c60",
          "sha1": "b275121e2ebc676150e7cc88e8bb698f037ac6aa",
          "md5": "f6785fc49a020ffb25c08bf16757a735"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gsyVideoPlayer-armv7a-1.4.2-sources.jar",
          "url": "gsyVideoPlayer-armv7a-1.4.2-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gsyVideoPlayer-armv7a-1.4.2-javadoc.jar",
          "url": "gsyVideoPlayer-armv7a-1.4.2-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
