{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.706412584",
    "module": "gsyVideoPlayer-proxy_cache",
    "version": "1.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gsyVideoPlayer-proxy_cache-1.4.2.aar",
          "url": "gsyVideoPlayer-proxy_cache-1.4.2.aar",
          "size": 55511,
          "sha512": "06c15284c6b8d90fdb123c95ac2e3d97dd5121e982c2c065fabbdb6fab25704efec3c0cb7accac84440cf21a7482a88b1d5f636e079246ba0a2e678f245ebe33",
          "sha256": "8d0f8d8c2e315b60970b9f3467d2c42d581589cc3abcbd8c0279ac9ad9a10b5c",
          "sha1": "102be6742efebe38a4d8d261704f50898d5cf558",
          "md5": "e1b1b6da634159b6e4ed9dbb0d3b7496"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "gsyVideoPlayer-proxy_cache-1.4.2.aar",
          "url": "gsyVideoPlayer-proxy_cache-1.4.2.aar",
          "size": 55511,
          "sha512": "06c15284c6b8d90fdb123c95ac2e3d97dd5121e982c2c065fabbdb6fab25704efec3c0cb7accac84440cf21a7482a88b1d5f636e079246ba0a2e678f245ebe33",
          "sha256": "8d0f8d8c2e315b60970b9f3467d2c42d581589cc3abcbd8c0279ac9ad9a10b5c",
          "sha1": "102be6742efebe38a4d8d261704f50898d5cf558",
          "md5": "e1b1b6da634159b6e4ed9dbb0d3b7496"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gsyVideoPlayer-proxy_cache-1.4.2-sources.jar",
          "url": "gsyVideoPlayer-proxy_cache-1.4.2-sources.jar",
          "size": 34747,
          "sha512": "fcd29c852cfc9ce4cf8fc2f100805ecbcc5c6f7a7ecc54c327eea59966a494bc2f4c72770b886806928ca7dd8fc81e9bf134b38ec46c94a682b5e5c23a99fc34",
          "sha256": "749c83b667c8dab1e0b800a2d0360d092ae2cd20945a5735ba5469987935ded8",
          "sha1": "9bee138745b4f5f237becf8718426133a7bd0e3e",
          "md5": "50491cf1955992e1b6eaedd41c9a8a8c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gsyVideoPlayer-proxy_cache-1.4.2-javadoc.jar",
          "url": "gsyVideoPlayer-proxy_cache-1.4.2-javadoc.jar",
          "size": 386444,
          "sha512": "d980ec2478c4b324194897047a3030686fcd41133ba7c0fb64d35b25b858c5699ca52fabb70625a8bf14e53381c91826f6a84a69e2ed778d224c4c6e3f76e8c4",
          "sha256": "6c012d01d2429c2b107a0fa16fd5319d81b1c5b4c9a5fd410114fee5cd4b11b6",
          "sha1": "72c02b6b624ebbd6bd79f411d2f532a7f66de136",
          "md5": "9c029b6ebddc92d76ad29909af5c649e"
        }
      ]
    }
  ]
}
