{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.706412584",
    "module": "gsyVideoPlayer-x86",
    "version": "1.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gsyVideoPlayer-x86-1.4.2.aar",
          "url": "gsyVideoPlayer-x86-1.4.2.aar",
          "size": 2984990,
          "sha512": "bf82d8cf202b8c422494574bf1f828b0ac50290d0a0b1bebc3903883a4a7e22f468b240198bae2e8b287e5d6f7cbcfa0d030b6ce91fa2d43b174551d43e32089",
          "sha256": "3838ebf8a23dbb2e646f5efb59ccc5017cd77f2168a829a86c45f1faaace51bf",
          "sha1": "637cb41cf3a3bafeec8180295b15cc2eb966a921",
          "md5": "d5d1827771a6cccd0955d84b75545e16"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "gsyVideoPlayer-x86-1.4.2.aar",
          "url": "gsyVideoPlayer-x86-1.4.2.aar",
          "size": 2984990,
          "sha512": "bf82d8cf202b8c422494574bf1f828b0ac50290d0a0b1bebc3903883a4a7e22f468b240198bae2e8b287e5d6f7cbcfa0d030b6ce91fa2d43b174551d43e32089",
          "sha256": "3838ebf8a23dbb2e646f5efb59ccc5017cd77f2168a829a86c45f1faaace51bf",
          "sha1": "637cb41cf3a3bafeec8180295b15cc2eb966a921",
          "md5": "d5d1827771a6cccd0955d84b75545e16"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gsyVideoPlayer-x86-1.4.2-sources.jar",
          "url": "gsyVideoPlayer-x86-1.4.2-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gsyVideoPlayer-x86-1.4.2-javadoc.jar",
          "url": "gsyVideoPlayer-x86-1.4.2-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
