{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.706412584",
    "module": "gsyVideoPlayer-ex_so",
    "version": "1.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gsyVideoPlayer-ex_so-1.4.2.aar",
          "url": "gsyVideoPlayer-ex_so-1.4.2.aar",
          "size": 15833960,
          "sha512": "c5bbf8939f37b620bdaca81a946a5a175c2c5a7f229cf6ac3d2bdb8ca966417ed49b8a4381a33f7cddcc6da18e0aa6cde8ba78386470909feebb73e697ea2539",
          "sha256": "bed83ac3106bfd6015475eb916194f7967ee642029117f4e708c2dc899751a4f",
          "sha1": "1cb1eef037d9a61a75d331e6f7931ed445a80d1d",
          "md5": "b246c626440d94a06ed59a1a293848f4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "gsyVideoPlayer-ex_so-1.4.2.aar",
          "url": "gsyVideoPlayer-ex_so-1.4.2.aar",
          "size": 15833960,
          "sha512": "c5bbf8939f37b620bdaca81a946a5a175c2c5a7f229cf6ac3d2bdb8ca966417ed49b8a4381a33f7cddcc6da18e0aa6cde8ba78386470909feebb73e697ea2539",
          "sha256": "bed83ac3106bfd6015475eb916194f7967ee642029117f4e708c2dc899751a4f",
          "sha1": "1cb1eef037d9a61a75d331e6f7931ed445a80d1d",
          "md5": "b246c626440d94a06ed59a1a293848f4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gsyVideoPlayer-ex_so-1.4.2-sources.jar",
          "url": "gsyVideoPlayer-ex_so-1.4.2-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gsyVideoPlayer-ex_so-1.4.2-javadoc.jar",
          "url": "gsyVideoPlayer-ex_so-1.4.2-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
